### ISSUE TITLE
 ( ! ) Fatal error: Uncaught exception 'Youtubedl\Exceptions\YoutubedlException' in D:\wamp\www\youtube_mp3_down_for_s60\Youtube_dl_php_master\src\Youtubedl\Youtubedl.php on line 64 ( ! ) Youtubedl\Exceptions\YoutubedlException: in D:\wamp\www\youtube_mp3_down_for_s60\Youtube_dl_php_master\src\Youtubedl\Youtubedl.php on line 64

### ISSUE THREAD

**Issue by blackholeearth** [J3-Tech/Youtube-dl-php#2]
( ! ) Fatal error: Uncaught exception 'Youtubedl\Exceptions\YoutubedlException' in D:\wamp\www\youtube_mp3_down_for_s60\Youtube_dl_php_master\src\Youtubedl\Youtubedl.php on line 64
( ! ) Youtubedl\Exceptions\YoutubedlException: in D:\wamp\www\youtube_mp3_down_for_s60\Youtube_dl_php_master\src\Youtubedl\Youtubedl.php on line 64

**Comment by chellem** [comment]
Hi, can you show what you have done to get this exception?
