### ISSUE TITLE
How to set youtube-dl params?

### ISSUE THREAD

**Issue by folkevil** [J3-Tech/Youtube-dl-php#7]
Hi,
How to set youtube-dl params, i tried but no luck.

**Comment by usamamashkoor** [comment]
did you find the solution..?

**Comment by amelia-bartlett** [comment]
You might need to look at the source - this project seems abandoned

**Comment by chellem** [comment]
May I know what params are you trying to pass?

The library accepts all parameters defined by the `youtube-dl`
