### ISSUE TITLE
Playlist Download

### ISSUE THREAD

**Issue by jonjieviduya** [J3-Tech/Youtube-dl-php#9]
Can we also have an option where we can download a playlist?

**Comment by chellem** [comment]
Hello, I think it's already in there.

Will check it and give you an example of how to do it.

**Comment by chellem** [comment]
This should do it.

```php
use Youtubedl\Youtubedl;

$youtubedl = new Youtubedl();
$youtubedl->isVerbose(true)
        ->download('PLAYLIST LINK')->execute();
```
